#pragma once

#define MAPSIZE 8
#define PLAYER_STARTPOS_Y (MAPSIZE/2)
#define PLAYER_STARTPOS_X (MAPSIZE/2)

#define OUTPUT_ENABLE_PIN D12
#define DATA_LINE_PIN D11
#define CLOCK_LINE_PIN D10
#define X_AXIS_PIN A2
#define Y_AXIS_PIN A1

#define DELAY_ROW_REFRESH_US 2000